image: alpine/edge
secrets:
  - b566bd73-a773-48ca-be59-7b88577d83eb
sources:
  - git@git.sr.ht/~mapperr/tsk
environment:
  GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
tasks:
  - setup: |
      # This is for not having to cd into your <repo> for each task
      echo 'cd tsk' >> ~/.buildenv
  - check: |
      if [ "$(git rev-parse origin/master)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi
  - mirror: |
      git push --force --mirror git@github.com:mapperr/tsk.git
