#! /bin/sh

cd "$(dirname $0)" >/dev/null
SCRIPTDIR="$(pwd -P)"
# =========================

if test -z "$SHUNIT_SCRIPT"; then
	echo "
    to run those tests set the SHUNIT_SCRIPT
    env var to the path of shunit2 script
    
    es: export SHUNIT_SCRIPT=\$HOME/shunit2/shunit2

    see this link for more infos:
    https://github.com/kward/shunit2"
	exit 1
fi

tsk="./tsk"

export TSK_DIR="/tmp/tskdir_test"
test -z "$TMPDIR" ||
	export TSK_DIR="$TMPDIR/tskdir_test"

logt() {
	local msg="$1"
	echo "TEST - $msg" >&2
}

cleanup() {
	if test -d "$TSK_DIR"; then
		rm -rf "$TSK_DIR"
	fi
}

setUp() {
	cleanup

	# import variables
	. $tsk test

	echo "$task_template" >$TSK_DIR/1.md
	echo "$task_template" >$TSK_DIR/2.md
	echo "$task_template" >$TSK_DIR/4.md
}

# tearDown() {
# 	cleanup
# }

test_rm_a_task() {
	yes | $tsk rm 4
	local n=$($tsk l | wc -l)
	assertTrue "test $n -eq 2"
}

test_mv_a_non_existent_task() {
	$tsk mv 5 3
	RET=$?
	assertTrue "test $RET -ne 0"
	assertFalse "$tsk ls | grep '^5'"
}

test_mv_the_same_task() {
	$tsk mv 4 4
	assertTrue " there should be a task with id 4" "$tsk ls | grep '^4'"
}

test_mv_a_task_to_an_empty_id() {
	$tsk mv 4 3
	assertTrue "$tsk ls | grep '^3'"
	assertFalse "$tsk ls | grep '^4'"
}

test_mv_a_task_to_a_non_empty_id() {
	$tsk mv 4 2
	$tsk gc
	assertFalse " a task with id 4 still exists" "$tsk ls | grep '^4'"
	assertTrue " there should be a task with id 2" "$tsk ls | grep '^2'"
	assertTrue " there should be a task with id 3" "$tsk ls | grep '^3'"
}

test_compact() {
	$tsk gc
	assertTrue "$tsk ls | grep '^3'"
}

. $SHUNIT_SCRIPT
