#! /bin/sh

cmd="$1"
test -z "$cmd" || shift

taskdir="$HOME/.tsk"

task_template="tags: 
title: 
due: 
description:
"

helpmsg() {
name=`basename $0`
echo "
$name ls | l [query]
    lists and searchs tasks
    
$name add | a
    adds a new task

$name edit | e task_id
    open EDITOR to edit a task, even if it not exists

$name rm | r task_id
    removes a task

$name mv | m task_id to_task_id
    moves a task to another id, shifting ids of other tasks

$name git | g [git_args]
    runs 'git git_args' in the task directory

$name sync | y
    syncs: commit changes and pull/push with git

$name clean
    purge your tasks, use with caution
"
}

logd(){
    local msg="$1"
    test -z "$TSK_DEBUG" || echo "DEBUG - $msg" >&2
} 

is_task_list_empty() {
    cd $taskdir
    ls -1 *.md >/dev/null 2>&1
    RET=$?
    cd - >/dev/null 2>&1
    test ! $RET = 0
}

get_task_file_list() {
    is_task_list_empty && return
    logd "taskdir: [$taskdir]"
    cd $taskdir
    file_list=`ls -1 *.md`
    logd "file list: [$file_list]"
    echo -n "$file_list"
    cd - >/dev/null 2>&1
}

get_task_id_list() {
    local file_list=`get_task_file_list`
    logd "file list for id list: [$file_list]"
    echo -n "$file_list" | sed 's/\.md$//g' | sort -rn
}

get_task_id_from_filename() {
    local filename="$1"
    basename "$filename" | sed 's/\.md$//'
}

get_task_field() {
    local task_id="$1"
    local field_name="$2"
    cat $taskdir/$task_id.md | grep "^$field_name:" | sed "s/^$field_name://"
}

list_tasks() {
    id_list=`get_task_id_list`
    logd "id list: [$id_list]"
    for task_id in $id_list; do
        title=`get_task_field $task_id 'title'`
        tags=`get_task_field $task_id 'tags'`
        tags=`for tag in $tags; do echo -n "[$tag] "; done`
        if echo -n "$task_id" |  grep '^[0-9]$' >/dev/null 2>&1; then
            echo "$task_id:  $tags$title"
        else
            echo "$task_id: $tags$title"
        fi
    done
}

is_there_a_task_with_id() {
    local task_id_to_check="$1"
    for task_id in `get_task_id_list`; do
        if [ "$task_id" = "$task_id_to_check" ]; then
            return 0
        fi
    done
    return 1
}

get_first_free_id() {
    counter=1
    while true; do
        if ! is_there_a_task_with_id $counter; then
            echo $counter
            return
        fi
        counter=`expr $counter + 1`
    done
}

get_new_id() {
    task_file_list=`get_task_file_list`
    if test -z "$task_file_list"; then
        echo 1
    else
        get_first_free_id
    fi
}

compact_ids() {
    id_list=`get_task_id_list | sort -n`
    counter=1
    cd $taskdir
    for id_ in $id_list; do
        if [ $id_ -ne $counter ]; then
            mv $id_.md $counter.md
        fi
        counter=`expr $counter + 1`
    done
    cd - >/dev/null 2>&1
}

add_task() {
    newid=`get_new_id`
    newfile=$taskdir/$newid.md
    echo "$task_template" > $newfile
    $EDITOR $newfile
}

edit_task() {
    local task_id="$1"
    $EDITOR $taskdir/$task_id.md
}

remove_task() {
    local task_id="$1"
    task_file="$taskdir/$task_id.md"
    if test ! -f $task_file; then
        echo "task $task_id does not exists"
        return
    fi
    title=`get_task_field $task_id 'title'`
    echo -n "remove task $task_id [$title] (y/n)? "
    read c
    if test "$c" = "y" || test "$c" = "Y"; then
        rm -f $task_file
        compact_ids
        echo "task $task_id removed"
    else
        echo "aborted"
    fi
}

move_task() {
    local from="$1"
    local to="$2"

    id_list=`get_task_id_list | sort -n`
    for id_ in $id_list; do
        if test "$id_" = "$to"; then
            cd $taskdir
            mv $to.md $to-moving.md
            mv $from.md $to.md
            mv $to-moving.md $from.md
            cd - >/dev/null 2>&1
        fi
    done
}

clean_tasks() {
    echo -n "delete all tasks (y/n)? "
    read c
    if test "$c" = "y" || test "$c" = "Y"; then
        rm -f $taskdir/*.md
        echo "tasks removed"
    else
        echo "aborted"
    fi
}

test -d $taskdir || mkdir -p $taskdir

if [ "$cmd" = "ls" ] || [ "$cmd" = "l" ]; then
    list_tasks

elif [ "$cmd" = "add" ] || [ "$cmd" = "a" ]; then
    add_task

elif [ "$cmd" = "edit" ] || [ "$cmd" = "e" ]; then
    edit_task $1

elif [ "$cmd" = "rm" ] || [ "$cmd" = "r" ]; then
    remove_task $1

elif [ "$cmd" = "mv" ] || [ "$cmd" = "m" ]; then
    from="$1"
    to="$2"
    if test -z "$from" || test -z "$to"; then
        helpmsg
        exit 1
    fi
    move_task $from $to

elif [ "$cmd" = "git" ] || [ "$cmd" = "g" ]; then
    cd $taskdir
    git $@

elif [ "$cmd" = "sync" ] || [ "$cmd" = "y" ]; then
    cd $taskdir
    git status | grep 'nothing to commit' >/dev/null 2>&1
    test $? = 1 && git add -A && git commit -am 'tsk autosync'
    git pull && git push

elif [ "$cmd" = "clean" ]; then
    clean_tasks

else
    helpmsg
fi
